# Generated by Django 2.2.19 on 2021-03-31 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_auto_20210331_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumeitem',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='gallery'),
        ),
    ]
